message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Checking new PR..."
        footer: ""
    updated:  # Messages when new commits are added to the PR
        header: "Checking updated PR..."
        footer: ""
    no_errors: "No PEP8 issues."

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown

pycodestyle:
    show-source: True
    max-line-length: 90 # Default is 80, but a little bit more is hardly a
                        # problem on any modern device and can aid readability
                        # by avoiding splits in self-contained lines.

    ignore:  # Errors and warnings to ignore

        - E126 # Limits split-line continuations to be indented only by 4 spaces.
               # This is not required by PEP8 and is often counterproductive for
               # readability, particularly when the following line is indented
               # to the same level and thus does not stand out as a new statement.

        - E225 # Whitespace around all infix operators. PEP8 requires only
               # that the whitespace should be the same on both sides of the
               # operator, but often it is more compact and readable to just
               # not have whitespace at all, particularly when writing
               # something like a*b + c.

        - E402
        - E741
        - W503
        - W504

no_blank_comment: False
only_mention_files_with_errors: True
descending_issues_order: True
