# Copyright 2014, 2015 The ODL development group
#
# This file is part of ODL.
#
# ODL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ODL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ODL.  If not, see <http://www.gnu.org/licenses/>.

"""Discretizations in ODL.

Abstract discretization classes (Module :mod:`~odl.discr.discretization`)
=========================================================================

+----------------------------+------------------------------------------------+
|Class name                  |Description                                     |
+============================+================================================+
|:class:`RawDiscretization`  |**Abstract** base class for discretizations     |
+----------------------------+------------------------------------------------+
|:class:`Discretization`     |**Abstract** base class for discretizations of  |
|                            |linear spaces                                   |
+----------------------------+------------------------------------------------+

Discretizations of L2 spaces (Module :mod:`~odl.discr.l2_discr`)
================================================================

+---------------------+-------------------------------------------------------+
|Class name           |Description                                            |
+=====================+=======================================================+
|:class:`DiscreteL2`  |Discretization of an :math:`L^2` space defined on an   |
|                     |interval product                                       |
+---------------------+-------------------------------------------------------+

Factory functions
-----------------

+------------------------------------+----------------------------------------+
|Name                                |Description                             |
+====================================+========================================+
|:class:`l2_uniform_discretization()`|Discretize an L2 space based on uniform |
|                                    |sampling and interpolation between      |
|                                    |samples                                 |
+------------------------------------+----------------------------------------+

Sampling grids (Module :mod:`~odl.discr.grid`)
==============================================

+----------------------------+------------------------------------------------+
|Class name                  |Description                                     |
+============================+================================================+
|:class:`TensorGrid`         |Tensor product of coordinate vectors, i.e.      |
|                            |points generated by all coordinate combinations |
+----------------------------+------------------------------------------------+
|:class:`RegularGrid`        |Tensor grid with regularly spaced coordinates   |
+----------------------------+------------------------------------------------+

Factory functions
-----------------

+--------------------------+-------------------------------------------------+
|Name                      |Description                                      |
+==========================+=================================================+
|:func:`uniform_sampling()`|Create a regular grid from an interval product   |
|                          |by uniform sampling                              |
+--------------------------+-------------------------------------------------+

Restriction and Extension operators (Module :mod:`~odl.discr.discr_mappings`)
=============================================================================

+----------------------------------+------------------------------------------+
|Class name                        |Description                               |
+==================================+==========================================+
|:class:`RawGridCollocation`       |Evaluation of functions in a function set |
|                                  |on a sampling grid                        |
+----------------------------------+------------------------------------------+
|:class:`GridCollocation`          |TODO write doc                            |
+----------------------------------+------------------------------------------+
|:class:`RawNearestInterpolation`  |TODO write doc                            |
+----------------------------------+------------------------------------------+
|:class:`NearestInterpolation`     |TODO write doc                            |
+----------------------------------+------------------------------------------+
|:class:`LinearInterpolation`      |TODO write doc                            |
+----------------------------------+------------------------------------------+
|:class:`CubicInterpolation`       |TODO implement                            |
+----------------------------------+------------------------------------------+
"""

from __future__ import absolute_import

__all__ = ()

from . import l2_discr
from .l2_discr import *
__all__ += l2_discr.__all__

from . import discretization
from .discretization import *
__all__ += discretization.__all__

from . import grid
from .grid import *
__all__ += grid.__all__

from . import discr_mappings
from .discr_mappings import *
__all__ += discr_mappings.__all__
