# Copyright 2014, 2015 The ODL development group
#
# This file is part of ODL.
#
# ODL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ODL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ODL.  If not, see <http://www.gnu.org/licenses/>.

"""Discretizations in ODL.

Abstract discretization classes (Module `discretization`)
=========================================================

+---------------------+------------------------------------------------+
|Class name           |Description                                     |
+=====================+================================================+
|``RawDiscretization``|**Abstract** base class for discretizations     |
+---------------------+------------------------------------------------+
|``Discretization``   |**Abstract** base class for discretizations of  |
|                     |linear spaces                                   |
+---------------------+------------------------------------------------+

Discretizations of default spaces (Module `default`)
====================================================

+--------------+-------------------------------------------------------+
|Class name    |Description                                            |
+==============+=======================================================+
|``DiscreteL2``|Discretization of an :math:`L^2` space defined on an   |
|              |interval product                                       |
+--------------+-------------------------------------------------------+

Sampling grids (Module `grid`)
==============================

+---------------------+------------------------------------------------+
|Class name           |Description                                     |
+=====================+================================================+
|``TensorGrid``       |Tensor product of coordinate vectors, i.e.      |
|                     |points generated by all coordinate combinations |
+---------------------+------------------------------------------------+
|``RegularGrid``      |Tensor grid with regularly spaced coordinates   |
+---------------------+------------------------------------------------+

Restriction and Extension operators (Module `operators`)
========================================================

+---------------------------+------------------------------------------+
|Class name                 |Description                               |
+===========================+==========================================+
|``RawGridCollocation``     |Evaluation of functions in a function set |
|                           |on a sampling grid                        |
+---------------------------+------------------------------------------+
|``GridCollocation``        |TODO                                      |
+---------------------------+------------------------------------------+
|``RawNearestInterpolation``|TODO                                      |
+---------------------------+------------------------------------------+
|``NearestInterpolation``   |TODO                                      |
+---------------------------+------------------------------------------+
"""

from __future__ import absolute_import

__all__ = []

from . import default
from .default import *
__all__ += default.__all__

from . import discretization
from .discretization import *
__all__ += discretization.__all__

from . import grid
from .grid import *
__all__ += grid.__all__

from . import operators
from .operators import *
__all__ += operators.__all__